### ISSUE TITLE
Export to ImgBB hits exhaustive 4xx rate limit

### ISSUE THREAD

**Issue by i0bs** [adhesivecheese/kinklist#10]
Hitting the export leads to a failed HTTP request to ImgBB's API:

```json
{"status_code":400,"error":{"message":"Rate limit reached.","code":100},"status_txt":"Bad Request"}
```

**Comment by i0bs** [comment]
Checked network stack calls - ImgBB API rate limits are scoped to the key provided. There should probably be an option somewhere in the HTML to use OAuth for logging in and auto-generating a key, e.g. Google, Twitter and etc.

Elevating issue @adhesivecheese

**Comment by Itay-Elenzweig** [comment]
Bumping this

**Comment by neonemily** [comment]
Bumping this - issue persists

`{"status_code":400,"error":{"message":"Rate limit reached.","code":100},"status_txt":"Bad Request"}`

**Comment by i0bs** [comment]
The only workaround currently is going through the network calls and manually modifying the token with your own in the minified JS file.

**Comment by adhesivecheese** [comment]
Fixed by reverting to imgur hosting
